INSERT INTO MEMBER (EMAIL, PASSWORD, NAME, NICKNAME, PHONE) SELECT 'test@test.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '테스트회원', 'testuser', '010-1111-2222' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MEMBER WHERE EMAIL = 'test@test.com');
COMMIT;

