-- SEOULLINK review demo: schema alignment + six review cards.
-- Open this file directly in SQL Developer and execute with F5.
-- This file is intentionally ASCII-only to avoid editor encoding corruption.

-- 1) Align the legacy COURSE_DETAILS primary key with CourseDetail.java.
DECLARE
    v_legacy_column_count NUMBER;
    v_target_column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_legacy_column_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COURSE_DETAILS' AND COLUMN_NAME = 'DETAIL_ID';

    SELECT COUNT(*) INTO v_target_column_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'COURSE_DETAILS' AND COLUMN_NAME = 'COURSE_DETAIL_ID';

    IF v_legacy_column_count = 1 AND v_target_column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE COURSE_DETAILS RENAME COLUMN DETAIL_ID TO COURSE_DETAIL_ID';
    END IF;
END;
/

-- 2) Add the review feature columns and tables when they do not already exist.
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE REVIEW ADD (COURSE_ID NUMBER, VISIT_DATE DATE, COMPANION VARCHAR2(30))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE REVIEW_IMAGE (
        REVIEW_IMAGE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_REVIEW_IMAGE PRIMARY KEY,
        REVIEW_ID NUMBER NOT NULL,
        IMAGE_URL VARCHAR2(1000) NOT NULL,
        DISPLAY_ORDER NUMBER NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT FK_REVIEW_IMAGE_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW(REVIEW_ID) ON DELETE CASCADE,
        CONSTRAINT CK_REVIEW_IMAGE_ORDER CHECK (DISPLAY_ORDER >= 1),
        CONSTRAINT UK_REVIEW_IMAGE_ORDER UNIQUE (REVIEW_ID, DISPLAY_ORDER)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE REVIEW_TAG (
        REVIEW_TAG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_REVIEW_TAG PRIMARY KEY,
        REVIEW_ID NUMBER NOT NULL,
        TAG_NAME VARCHAR2(30) NOT NULL,
        CONSTRAINT FK_REVIEW_TAG_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW(REVIEW_ID) ON DELETE CASCADE,
        CONSTRAINT UK_REVIEW_TAG UNIQUE (REVIEW_ID, TAG_NAME)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3) Insert reusable places, one course, six reviews, images, tags, and a comment.
DECLARE
    v_member_id MEMBER.MEMBER_ID%TYPE;
    v_bukchon_id PLACES.PLACE_ID%TYPE;
    v_namsan_id PLACES.PLACE_ID%TYPE;
    v_ikseon_id PLACES.PLACE_ID%TYPE;
    v_course_id TRAVEL_COURSES.COURSE_ID%TYPE;
    v_review_id REVIEW.REVIEW_ID%TYPE;

    PROCEDURE ensure_place(
        p_api_id VARCHAR2, p_name VARCHAR2, p_region VARCHAR2,
        p_address VARCHAR2, p_lat NUMBER, p_lng NUMBER, p_id OUT NUMBER
    ) IS
    BEGIN
        SELECT PLACE_ID INTO p_id
        FROM PLACES
        WHERE API_PROVIDER = 'SEOULLINK_DEMO' AND API_PLACE_ID = p_api_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO PLACES (
                API_PROVIDER, API_PLACE_ID, NAME, CATEGORY, REGION, ADDRESS,
                LATITUDE, LONGITUDE, RATING, REVIEW_COUNT, IS_ACTIVE
            ) VALUES (
                'SEOULLINK_DEMO', p_api_id, p_name, 'TOUR', p_region, p_address,
                p_lat, p_lng, 0, 0, 'Y'
            ) RETURNING PLACE_ID INTO p_id;
    END;

    PROCEDURE add_review(
        p_title VARCHAR2, p_content VARCHAR2, p_rating NUMBER, p_place_id NUMBER,
        p_visit_date DATE, p_companion VARCHAR2, p_image VARCHAR2,
        p_tag1 VARCHAR2, p_tag2 VARCHAR2
    ) IS
    BEGIN
        INSERT INTO REVIEW (
            MEMBER_ID, PLACE_ID, COURSE_ID, REVIEW_TITLE, REVIEW_CONTENT, RATING,
            IMAGE_URL, VISIT_DATE, COMPANION, VIEW_COUNT, IS_DELETED
        ) VALUES (
            v_member_id, p_place_id, v_course_id, p_title, p_content, p_rating,
            p_image, p_visit_date, p_companion, 0, 'N'
        ) RETURNING REVIEW_ID INTO v_review_id;

        INSERT INTO REVIEW_IMAGE (REVIEW_ID, IMAGE_URL, DISPLAY_ORDER)
        VALUES (v_review_id, p_image, 1);
        INSERT INTO REVIEW_TAG (REVIEW_ID, TAG_NAME) VALUES (v_review_id, p_tag1);
        INSERT INTO REVIEW_TAG (REVIEW_ID, TAG_NAME) VALUES (v_review_id, p_tag2);
    END;
BEGIN
    SELECT MEMBER_ID INTO v_member_id
    FROM (SELECT MEMBER_ID FROM MEMBER WHERE STATUS = 'ACTIVE' ORDER BY MEMBER_ID)
    WHERE ROWNUM = 1;

    ensure_place('BUKCHON_V3', 'Bukchon Hanok Village', 'Jongno-gu, Seoul', 'Gye-dong, Jongno-gu, Seoul', 37.5826, 126.9830, v_bukchon_id);
    ensure_place('NAMSAN_V3', 'N Seoul Tower', 'Yongsan-gu, Seoul', 'Namsan Park-gil 105, Yongsan-gu, Seoul', 37.5512, 126.9882, v_namsan_id);
    ensure_place('IKSEONDONG_V3', 'Ikseon-dong Hanok Street', 'Jongno-gu, Seoul', 'Ikseon-dong, Jongno-gu, Seoul', 37.5730, 126.9897, v_ikseon_id);

    BEGIN
        SELECT COURSE_ID INTO v_course_id
        FROM TRAVEL_COURSES
        WHERE MEMBER_ID = v_member_id AND TITLE = '[DEMO V3] Seoul Day Walk';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO TRAVEL_COURSES (
                MEMBER_ID, TITLE, DESCRIPTION, COURSE_TYPE, REGION, IS_PUBLIC, VIEW_COUNT
            ) VALUES (
                v_member_id, '[DEMO V3] Seoul Day Walk',
                'A relaxed route through Bukchon, Ikseon-dong, and Namsan.', 'CUSTOM', 'Seoul', 'Y', 0
            ) RETURNING COURSE_ID INTO v_course_id;
    END;

    DELETE FROM COURSE_DETAILS WHERE COURSE_ID = v_course_id;
    INSERT INTO COURSE_DETAILS (COURSE_ID, PLACE_ID, DAY_NO, PLACE_ORDER, VISIT_TIME, MEMO)
    VALUES (v_course_id, v_bukchon_id, 1, 1, '09:30', 'Walk through the quiet hanok alley.');
    INSERT INTO COURSE_DETAILS (COURSE_ID, PLACE_ID, DAY_NO, PLACE_ORDER, VISIT_TIME, MEMO)
    VALUES (v_course_id, v_ikseon_id, 1, 2, '14:00', 'Take a relaxed cafe break.');
    INSERT INTO COURSE_DETAILS (COURSE_ID, PLACE_ID, DAY_NO, PLACE_ORDER, VISIT_TIME, MEMO)
    VALUES (v_course_id, v_namsan_id, 1, 3, '19:00', 'Enjoy the Seoul night view.');

    DELETE FROM REVIEW WHERE REVIEW_TITLE LIKE '[DEMO V3] %';

    add_review('[DEMO V3] A Quiet Morning in Bukchon',
        'Golden morning light made the hanok roofs glow. The calm lanes were perfect for a slow Seoul walk.',
        4.9, v_bukchon_id, DATE '2026-07-12', 'Solo', '/review-seed/bukchon-sunrise-v2.png', 'solo', 'photo spot');
    add_review('[DEMO V3] Hanok Details and City Views',
        'An early visit made it easy to notice the traditional details and the city skyline beyond the village.',
        4.8, v_bukchon_id, DATE '2026-07-10', 'Friends', '/review-seed/bukchon-sunrise-v2.png', 'date', 'Seoul walk');
    add_review('[DEMO V3] An Afternoon Cafe in Ikseon-dong',
        'The hanok cafe was warm and peaceful, with plants and soft lighting that made the alley feel special.',
        4.7, v_ikseon_id, DATE '2026-07-08', 'Friends', '/review-seed/ikseondong-cafe-v2.png', 'cafe tour', 'food');
    add_review('[DEMO V3] Seoul Lights from Namsan',
        'The city lights from the observatory were unforgettable. Visit on a clear evening for the best view.',
        4.9, v_namsan_id, DATE '2026-07-06', 'Couple', '/review-seed/namsan-night-v2.png', 'night view', 'date');
    add_review('[DEMO V3] A Family Night at Namsan',
        'The cable car ride and the wide city view made this an easy favorite for a family Seoul outing.',
        4.8, v_namsan_id, DATE '2026-07-03', 'Family', '/review-seed/namsan-night-v2.png', 'family', 'night view');
    add_review('[DEMO V3] A Seoul Alley Worth Returning To',
        'Hanok alleys, a cozy cafe, and a city night view made this a complete one-day Seoul route.',
        4.8, v_ikseon_id, DATE '2026-07-01', 'Solo', '/review-seed/ikseondong-cafe-v2.png', 'solo', 'cafe tour');

    INSERT INTO REVIEW_COMMENT (REVIEW_ID, MEMBER_ID, CONTENT, IS_DELETED)
    VALUES (v_review_id, v_member_id, 'This is a lovely Seoul itinerary. I will save it for my next trip.', 'N');

    UPDATE PLACES p
    SET RATING = (SELECT AVG(r.RATING) FROM REVIEW r WHERE r.PLACE_ID = p.PLACE_ID AND r.IS_DELETED = 'N'),
        REVIEW_COUNT = (SELECT COUNT(*) FROM REVIEW r WHERE r.PLACE_ID = p.PLACE_ID AND r.IS_DELETED = 'N')
    WHERE p.PLACE_ID IN (v_bukchon_id, v_namsan_id, v_ikseon_id);

    COMMIT;
END;
/
