spring.application.name=seoul-link-back

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=seoulink
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-4.1-mini

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true