spring.application.name=seoul-link-back

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=seoulink
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver



openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-4.1-mini

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.front-url=http://localhost:5173
app.demo-signup-pass-enabled=${DEMO_SIGNUP_PASS_ENABLED:true}

oauth.kakao.client-id=카카오_REST_API_KEY
oauth.kakao.client-secret=카카오_CLIENT_SECRET
oauth.kakao.redirect-uri=http://localhost:8080/api/members/oauth/kakao/callback

oauth.naver.client-id=네이버_CLIENT_ID
oauth.naver.client-secret=네이버_CLIENT_SECRET
oauth.naver.redirect-uri=http://localhost:8080/api/members/oauth/naver/callback

oauth.google.client-id=구글_CLIENT_ID
oauth.google.client-secret=구글_CLIENT_SECRET
oauth.google.redirect-uri=http://localhost:8080/api/members/oauth/google/callback

portone.api-url=https://api.portone.io
portone.api-secret=${PORTONE_API_SECRET}
portone.store-id=${PORTONE_STORE_ID}
portone.webhook-secret=${PORTONE_WEBHOOK_SECRET:}
