-- 추천받은 모든 코스와 사용자가 저장한 내 코스를 분리하기 위한 기존 DB 적용 파일
-- 기존 TRAVEL_COURSES 행은 이미 저장된 코스이므로 기본값 Y로 보존합니다.

DECLARE
    V_COLUMN_COUNT     NUMBER;
    V_CONSTRAINT_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_COLUMN_COUNT
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TRAVEL_COURSES'
       AND COLUMN_NAME = 'IS_SAVED';

    IF V_COLUMN_COUNT = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE TRAVEL_COURSES
            ADD IS_SAVED CHAR(1) DEFAULT ''Y'' NOT NULL
        ';
    END IF;

    SELECT COUNT(*)
      INTO V_CONSTRAINT_COUNT
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'TRAVEL_COURSES'
       AND CONSTRAINT_NAME = 'CK_COURSE_SAVED';

    IF V_CONSTRAINT_COUNT = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE TRAVEL_COURSES
            ADD CONSTRAINT CK_COURSE_SAVED
            CHECK (IS_SAVED IN (''Y'', ''N''))
        ';
    END IF;
END;
/

COMMENT ON COLUMN TRAVEL_COURSES.IS_SAVED IS
    '추천 이력 중 사용자가 내 코스에 저장했는지 여부, Y/N';

COMMIT;

SELECT COURSE_ID, COURSE_TYPE, IS_SAVED, TITLE
  FROM TRAVEL_COURSES
 ORDER BY CREATED_AT DESC, COURSE_ID DESC;
