/*
 * 기존 SEOULINK Oracle DB에만 1회 실행한다.
 * 새 DB를 database/seoulink.sql로 만드는 경우에는 이 파일을 따로 실행하지 않는다.
 */

ALTER TABLE COURSE_DETAILS
ADD ROUTE_ESTIMATED NUMBER(1) DEFAULT 0 NOT NULL;

ALTER TABLE COURSE_DETAILS
ADD CONSTRAINT CK_COURSE_DETAILS_ROUTE_ESTIMATED
CHECK (ROUTE_ESTIMATED IN (0, 1));

ALTER TABLE COURSE_DETAILS
DROP CONSTRAINT CK_COURSE_DETAILS_TRANSIT_PATH;

ALTER TABLE COURSE_DETAILS
ADD CONSTRAINT CK_COURSE_DETAILS_TRANSIT_PATH
CHECK (
    TRANSIT_PATH_TYPE IS NULL
    OR TRANSIT_PATH_TYPE IN (
        'WALKING',
        'SUBWAY',
        'BUS',
        'BUS_SUBWAY'
    )
);

COMMENT ON COLUMN COURSE_DETAILS.ROUTE_ESTIMATED
IS '외부 경로 조회 실패로 추정값을 사용했으면 1, 실제 경로면 0';

COMMENT ON COLUMN COURSE_DETAILS.TRANSIT_PATH_TYPE
IS '대중교통 선택 시 실제 구간 종류, WALKING/SUBWAY/BUS/BUS_SUBWAY';

COMMIT;
