/*
 * SEOULINK 최종 통합 스키마
 * - 사용자 기존 SQL을 기준으로 팀 통합 SQL의 변경 사항을 반영
 * - 실행 시 기존 SEOULINK 테이블과 데이터가 삭제된 후 다시 생성됨
 */

-- 테이블이 아직 없어도 중단되지 않도록 자식 테이블부터 안전하게 삭제
DECLARE
TYPE TABLE_NAME_LIST IS TABLE OF VARCHAR2(30);
    TABLE_NAMES TABLE_NAME_LIST := TABLE_NAME_LIST(
        'REVIEW_COMMENT',
        'REVIEW_LIKE',
        'REVIEW',
        'CHATBOT_HISTORY',
        'COURSE_DETAILS',
        'TRAVEL_COURSES',
        'SURVEY_RESULT',
        'TRAVEL_TYPE_PLACE',
        'SURVEY_ANSWER',
        'TRAVEL_SURVEY',
        'PAYMENT',
        'PLACES',
        'SURVEY_OPTION',
        'SURVEY_QUESTION',
        'TRAVEL_TYPE_MASTER',
        'MEMBER'
    );
BEGIN
FOR I IN 1 .. TABLE_NAMES.COUNT LOOP
BEGIN
EXECUTE IMMEDIATE
    'DROP TABLE ' || TABLE_NAMES(I) || ' CASCADE CONSTRAINTS';
EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN
                    RAISE;
END IF;
END;
END LOOP;
END;

-- MEMBER
CREATE TABLE MEMBER (
                        MEMBER_ID NUMBER GENERATED ALWAYS AS IDENTITY
                            CONSTRAINT PK_MEMBER PRIMARY KEY,

                        EMAIL VARCHAR2(100) NOT NULL,
                        PASSWORD VARCHAR2(255) NOT NULL,
                        NAME VARCHAR2(50) NOT NULL,
                        NICKNAME VARCHAR2(50),
                        PHONE VARCHAR2(20),

                        LOGIN_TYPE VARCHAR2(20) DEFAULT 'LOCAL' NOT NULL,

                        STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

                        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
                        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,

                        CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),
                        CONSTRAINT UK_MEMBER_NICKNAME UNIQUE (NICKNAME),

                        CONSTRAINT CK_MEMBER_STATUS
                            CHECK (STATUS IN ('ACTIVE', 'WITHDRAWN'))
);

-- TRAVEL_TYPE_MASTER
CREATE TABLE TRAVEL_TYPE_MASTER (
                                    TRAVEL_CODE CHAR(5)
                                        CONSTRAINT PK_TRAVEL_TYPE PRIMARY KEY,

                                    TYPE_TITLE VARCHAR2(100) NOT NULL,
                                    TYPE_DESCRIPTION VARCHAR2(2000) NOT NULL,
                                    IMAGE_URL VARCHAR2(500)
);

-- SURVEY_QUESTION
CREATE TABLE SURVEY_QUESTION (
                                 QUESTION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT PK_SURVEY_QUESTION PRIMARY KEY,

                                 QUESTION_TEXT VARCHAR2(500) NOT NULL,
                                 CATEGORY VARCHAR2(30) NOT NULL
);

-- SURVEY_OPTION
CREATE TABLE SURVEY_OPTION (
                               OPTION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                   CONSTRAINT PK_SURVEY_OPTION PRIMARY KEY,

                               QUESTION_ID NUMBER NOT NULL,
                               OPTION_TEXT VARCHAR2(300) NOT NULL,
                               SCORE_CODE VARCHAR2(20) NOT NULL,
                               SCORE_VALUE NUMBER DEFAULT 1 NOT NULL,

                               CONSTRAINT FK_OPTION_QUESTION
                                   FOREIGN KEY (QUESTION_ID)
                                       REFERENCES SURVEY_QUESTION(QUESTION_ID)
                                       ON DELETE CASCADE,

                               CONSTRAINT UK_OPTION_QUESTION
                                   UNIQUE (QUESTION_ID, OPTION_ID)
);

-- PLACES
CREATE TABLE PLACES (
                        PLACE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                            CONSTRAINT PK_PLACES PRIMARY KEY,

                        API_PROVIDER VARCHAR2(30) NOT NULL,
                        API_PLACE_ID VARCHAR2(100) NOT NULL,
                        CONTENT_ID NUMBER,

                        NAME VARCHAR2(200) NOT NULL,
                        CATEGORY VARCHAR2(50) NOT NULL,
                        API_CATEGORY VARCHAR2(200),

                        REGION VARCHAR2(100) NOT NULL,
                        ADDRESS VARCHAR2(500) NOT NULL,
                        ROAD_ADDRESS VARCHAR2(500),

                        LATITUDE NUMBER(10, 7) NOT NULL,
                        LONGITUDE NUMBER(10, 7) NOT NULL,

                        PHONE VARCHAR2(50),
                        PLACE_URL VARCHAR2(1000),

                        RATING NUMBER(3, 2) DEFAULT 0.0 NOT NULL,
                        REVIEW_COUNT NUMBER DEFAULT 0 NOT NULL,

                        DESCRIPTION CLOB,
                        IMAGE_URL VARCHAR2(1000),

                        TAG_HISTORY CHAR(1) DEFAULT 'N' NOT NULL,
                        TAG_MODERN CHAR(1) DEFAULT 'N' NOT NULL,
                        TAG_BUDGET CHAR(1) DEFAULT 'N' NOT NULL,
                        TAG_LUXURY CHAR(1) DEFAULT 'N' NOT NULL,
                        TAG_STABLE CHAR(1) DEFAULT 'N' NOT NULL,
                        TAG_DOPAMINE CHAR(1) DEFAULT 'N' NOT NULL,
                        TAG_RELAX CHAR(1) DEFAULT 'N' NOT NULL,
                        TAG_PACKED CHAR(1) DEFAULT 'N' NOT NULL,

                        IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,

                        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
                        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,

                        CONSTRAINT UK_PLACES_API
                            UNIQUE (API_PROVIDER, API_PLACE_ID),

                        CONSTRAINT CK_PLACES_CATEGORY
                            CHECK (CATEGORY IN ('TOUR', 'RESTAURANT', 'CAFE', 'HOTEL')),

                        CONSTRAINT CK_PLACES_RATING
                            CHECK (RATING BETWEEN 0 AND 5),

                        CONSTRAINT CK_PLACES_REVIEW_COUNT
                            CHECK (REVIEW_COUNT >= 0),

                        CONSTRAINT CK_PLACES_LATITUDE
                            CHECK (LATITUDE BETWEEN -90 AND 90),

                        CONSTRAINT CK_PLACES_LONGITUDE
                            CHECK (LONGITUDE BETWEEN -180 AND 180),

                        CONSTRAINT CK_PLACES_HISTORY CHECK (TAG_HISTORY IN ('Y', 'N')),
                        CONSTRAINT CK_PLACES_MODERN CHECK (TAG_MODERN IN ('Y', 'N')),
                        CONSTRAINT CK_PLACES_BUDGET CHECK (TAG_BUDGET IN ('Y', 'N')),
                        CONSTRAINT CK_PLACES_LUXURY CHECK (TAG_LUXURY IN ('Y', 'N')),
                        CONSTRAINT CK_PLACES_STABLE CHECK (TAG_STABLE IN ('Y', 'N')),
                        CONSTRAINT CK_PLACES_DOPAMINE CHECK (TAG_DOPAMINE IN ('Y', 'N')),
                        CONSTRAINT CK_PLACES_RELAX CHECK (TAG_RELAX IN ('Y', 'N')),
                        CONSTRAINT CK_PLACES_PACKED CHECK (TAG_PACKED IN ('Y', 'N')),
                        CONSTRAINT CK_PLACES_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- PAYMENT
CREATE TABLE PAYMENT (
                         PAYMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                             CONSTRAINT PK_PAYMENT PRIMARY KEY,

                         MEMBER_ID NUMBER NOT NULL,

                         PRODUCT_NAME VARCHAR2(100) NOT NULL,
                         AMOUNT NUMBER DEFAULT 0 NOT NULL,

                         PAYMENT_METHOD VARCHAR2(30) NOT NULL,
                         PAYMENT_PROVIDER VARCHAR2(30),

                         ORDER_ID VARCHAR2(100) NOT NULL,
                         PAYMENT_KEY VARCHAR2(200),

                         PAYMENT_STATUS VARCHAR2(20) DEFAULT 'READY' NOT NULL,

                         REMAIN_COUNT NUMBER DEFAULT 0 NOT NULL,
                         EXPIRED_AT DATE,

                         PAID_AT DATE,
                         CANCELED_AT DATE,
                         FAIL_REASON VARCHAR2(500),

                         CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

                         CONSTRAINT FK_PAYMENT_MEMBER
                             FOREIGN KEY (MEMBER_ID)
                                 REFERENCES MEMBER(MEMBER_ID),

                         CONSTRAINT UK_PAYMENT_ORDER
                             UNIQUE (ORDER_ID),

                         CONSTRAINT CK_PAYMENT_AMOUNT
                             CHECK (AMOUNT >= 0),

                         CONSTRAINT CK_PAYMENT_REMAIN
                             CHECK (REMAIN_COUNT >= 0),

                         CONSTRAINT CK_PAYMENT_STATUS
                             CHECK (PAYMENT_STATUS IN ('READY', 'PAID', 'CANCELED', 'FAILED'))
);

-- TRAVEL_SURVEY
CREATE TABLE TRAVEL_SURVEY (
                               SURVEY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                   CONSTRAINT PK_TRAVEL_SURVEY PRIMARY KEY,

                               MEMBER_ID NUMBER,
                               GUEST_TOKEN VARCHAR2(100),

                               REGION VARCHAR2(50) NOT NULL,
                               START_DATE DATE NOT NULL,
                               END_DATE DATE NOT NULL,
                               PEOPLE_COUNT NUMBER NOT NULL,

                               CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

                               CONSTRAINT FK_SURVEY_MEMBER
                                   FOREIGN KEY (MEMBER_ID)
                                       REFERENCES MEMBER(MEMBER_ID)
                                       ON DELETE CASCADE,

                               CONSTRAINT UK_SURVEY_GUEST_TOKEN
                                   UNIQUE (GUEST_TOKEN),

                               CONSTRAINT CK_SURVEY_OWNER
                                   CHECK (MEMBER_ID IS NOT NULL OR GUEST_TOKEN IS NOT NULL),

                               CONSTRAINT CK_SURVEY_DATE
                                   CHECK (END_DATE >= START_DATE),

                               CONSTRAINT CK_SURVEY_PEOPLE
                                   CHECK (PEOPLE_COUNT >= 1)
);

-- SURVEY_ANSWER
CREATE TABLE SURVEY_ANSWER (
                               ANSWER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                   CONSTRAINT PK_SURVEY_ANSWER PRIMARY KEY,

                               SURVEY_ID NUMBER NOT NULL,
                               QUESTION_ID NUMBER NOT NULL,
                               OPTION_ID NUMBER NOT NULL,

                               CONSTRAINT FK_ANSWER_SURVEY
                                   FOREIGN KEY (SURVEY_ID)
                                       REFERENCES TRAVEL_SURVEY(SURVEY_ID)
                                       ON DELETE CASCADE,

                               CONSTRAINT FK_ANSWER_QUESTION
                                   FOREIGN KEY (QUESTION_ID)
                                       REFERENCES SURVEY_QUESTION(QUESTION_ID),

                               CONSTRAINT FK_ANSWER_OPTION
                                   FOREIGN KEY (QUESTION_ID, OPTION_ID)
                                       REFERENCES SURVEY_OPTION(QUESTION_ID, OPTION_ID),

                               CONSTRAINT UK_ANSWER_SURVEY_QUESTION
                                   UNIQUE (SURVEY_ID, QUESTION_ID)
);

-- TRAVEL_TYPE_PLACE
CREATE TABLE TRAVEL_TYPE_PLACE (
                                   TYPE_PLACE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                       CONSTRAINT PK_TRAVEL_TYPE_PLACE PRIMARY KEY,

                                   TRAVEL_CODE CHAR(5) NOT NULL,
                                   PLACE_ID NUMBER NOT NULL,

                                   WEIGHT_SCORE NUMBER DEFAULT 1 NOT NULL,

                                   CONSTRAINT FK_TYPE_PLACE_TYPE
                                       FOREIGN KEY (TRAVEL_CODE)
                                           REFERENCES TRAVEL_TYPE_MASTER(TRAVEL_CODE)
                                           ON DELETE CASCADE,

                                   CONSTRAINT FK_TYPE_PLACE_PLACE
                                       FOREIGN KEY (PLACE_ID)
                                           REFERENCES PLACES(PLACE_ID)
                                           ON DELETE CASCADE,

                                   CONSTRAINT UK_TYPE_PLACE
                                       UNIQUE (TRAVEL_CODE, PLACE_ID),

                                   CONSTRAINT CK_TYPE_PLACE_WEIGHT
                                       CHECK (WEIGHT_SCORE >= 0)
);

-- SURVEY_RESULT
CREATE TABLE SURVEY_RESULT (
                               RESULT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                   CONSTRAINT PK_SURVEY_RESULT PRIMARY KEY,

                               SURVEY_ID NUMBER NOT NULL,
                               TRAVEL_CODE CHAR(5) NOT NULL,

                               WEATHER_STATUS VARCHAR2(50),
                               TEMPERATURE NUMBER(4, 1),
                               RAIN_PROBABILITY NUMBER,

                               CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

                               CONSTRAINT UK_RESULT_SURVEY
                                   UNIQUE (SURVEY_ID),

                               CONSTRAINT FK_RESULT_SURVEY
                                   FOREIGN KEY (SURVEY_ID)
                                       REFERENCES TRAVEL_SURVEY(SURVEY_ID)
                                       ON DELETE CASCADE,

                               CONSTRAINT FK_RESULT_TYPE
                                   FOREIGN KEY (TRAVEL_CODE)
                                       REFERENCES TRAVEL_TYPE_MASTER(TRAVEL_CODE),

                               CONSTRAINT CK_RESULT_RAIN
                                   CHECK (RAIN_PROBABILITY IS NULL OR RAIN_PROBABILITY BETWEEN 0 AND 100)
);

-- TRAVEL_COURSES
CREATE TABLE TRAVEL_COURSES (
                                COURSE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                    CONSTRAINT PK_TRAVEL_COURSES PRIMARY KEY,

                                MEMBER_ID NUMBER NOT NULL,

                                RESULT_ID NUMBER,
                                PAYMENT_ID NUMBER,

                                TITLE VARCHAR2(200) NOT NULL,
                                DESCRIPTION CLOB,

                                TRAVEL_CODE CHAR(5),

                                COURSE_TYPE VARCHAR2(20) DEFAULT 'CUSTOM' NOT NULL,

                                REGION VARCHAR2(100),

                                IS_PUBLIC CHAR(1) DEFAULT 'N' NOT NULL,

                                VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,

                                TOTAL_DISTANCE_KM NUMBER(12, 3) DEFAULT 0 NOT NULL,
                                TOTAL_TRAVEL_MINUTES NUMBER(12, 2) DEFAULT 0 NOT NULL,
                                TOTAL_VISIT_MINUTES NUMBER DEFAULT 0 NOT NULL,
                                TOTAL_COURSE_MINUTES NUMBER(12, 2) DEFAULT 0 NOT NULL,

                                CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
                                UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,

                                CONSTRAINT FK_COURSE_MEMBER
                                    FOREIGN KEY (MEMBER_ID)
                                        REFERENCES MEMBER(MEMBER_ID)
                                        ON DELETE CASCADE,

                                CONSTRAINT FK_COURSE_RESULT
                                    FOREIGN KEY (RESULT_ID)
                                        REFERENCES SURVEY_RESULT(RESULT_ID),

                                CONSTRAINT FK_COURSE_PAYMENT
                                    FOREIGN KEY (PAYMENT_ID)
                                        REFERENCES PAYMENT(PAYMENT_ID),

                                CONSTRAINT FK_COURSE_TYPE
                                    FOREIGN KEY (TRAVEL_CODE)
                                        REFERENCES TRAVEL_TYPE_MASTER(TRAVEL_CODE),

                                CONSTRAINT CK_COURSE_TYPE
                                    CHECK (COURSE_TYPE IN ('CUSTOM', 'SURVEY', 'CHATBOT')),

                                CONSTRAINT CK_COURSE_PUBLIC
                                    CHECK (IS_PUBLIC IN ('Y', 'N')),

                                CONSTRAINT CK_COURSE_VIEW_COUNT
                                    CHECK (VIEW_COUNT >= 0),

                                CONSTRAINT CK_COURSE_TOTAL_DISTANCE
                                    CHECK (TOTAL_DISTANCE_KM >= 0),

                                CONSTRAINT CK_COURSE_TOTAL_TRAVEL
                                    CHECK (TOTAL_TRAVEL_MINUTES >= 0),

                                CONSTRAINT CK_COURSE_TOTAL_VISIT
                                    CHECK (TOTAL_VISIT_MINUTES >= 0),

                                CONSTRAINT CK_COURSE_TOTAL_TIME
                                    CHECK (TOTAL_COURSE_MINUTES >= 0)
);

-- COURSE_DETAILS
CREATE TABLE COURSE_DETAILS (
                                DETAIL_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                    CONSTRAINT PK_COURSE_DETAILS PRIMARY KEY,

                                COURSE_ID NUMBER NOT NULL,
                                PLACE_ID NUMBER NOT NULL,

                                DAY_NO NUMBER DEFAULT 1 NOT NULL,
                                PLACE_ORDER NUMBER NOT NULL,

                                MEMO VARCHAR2(500),
                                VISIT_TIME VARCHAR2(50),
                                STAY_MINUTES NUMBER,

                                VISIT_DATE DATE,
                                DISTANCE_FROM_PREV_KM NUMBER(12, 3) DEFAULT 0 NOT NULL,
                                TRAVEL_MINUTES_FROM_PREV NUMBER(12, 2) DEFAULT 0 NOT NULL,

                                CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

                                CONSTRAINT FK_DETAILS_COURSE
                                    FOREIGN KEY (COURSE_ID)
                                        REFERENCES TRAVEL_COURSES(COURSE_ID)
                                        ON DELETE CASCADE,

                                CONSTRAINT FK_DETAILS_PLACE
                                    FOREIGN KEY (PLACE_ID)
                                        REFERENCES PLACES(PLACE_ID),

                                CONSTRAINT UK_COURSE_ORDER
                                    UNIQUE (COURSE_ID, DAY_NO, PLACE_ORDER),

                                CONSTRAINT CK_COURSE_DAY
                                    CHECK (DAY_NO >= 1),

                                CONSTRAINT CK_COURSE_ORDER
                                    CHECK (PLACE_ORDER >= 1),

                                CONSTRAINT CK_COURSE_STAY
                                    CHECK (STAY_MINUTES IS NULL OR STAY_MINUTES >= 0),

                                CONSTRAINT CK_DETAIL_PREV_DISTANCE
                                    CHECK (DISTANCE_FROM_PREV_KM >= 0),

                                CONSTRAINT CK_DETAIL_PREV_TRAVEL
                                    CHECK (TRAVEL_MINUTES_FROM_PREV >= 0)
);

-- CHATBOT_HISTORY
CREATE TABLE CHATBOT_HISTORY (
                                 CHAT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT PK_CHATBOT_HISTORY PRIMARY KEY,

                                 MEMBER_ID NUMBER NOT NULL,

                                 PAYMENT_ID NUMBER,
                                 RESULT_ID NUMBER,
                                 COURSE_ID NUMBER,

                                 QUESTION CLOB NOT NULL,
                                 TRAVEL_CONCEPT VARCHAR2(100) NOT NULL,
                                 ANSWER CLOB NOT NULL,
                                 COURSE_SUMMARY CLOB,

                                 CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

                                 CONSTRAINT FK_CHATBOT_MEMBER
                                     FOREIGN KEY (MEMBER_ID)
                                         REFERENCES MEMBER(MEMBER_ID)
                                         ON DELETE CASCADE,

                                 CONSTRAINT FK_CHATBOT_PAYMENT
                                     FOREIGN KEY (PAYMENT_ID)
                                         REFERENCES PAYMENT(PAYMENT_ID),

                                 CONSTRAINT FK_CHATBOT_RESULT
                                     FOREIGN KEY (RESULT_ID)
                                         REFERENCES SURVEY_RESULT(RESULT_ID),

                                 CONSTRAINT FK_CHATBOT_COURSE
                                     FOREIGN KEY (COURSE_ID)
                                         REFERENCES TRAVEL_COURSES(COURSE_ID)
);

-- REVIEW
CREATE TABLE REVIEW (
                        REVIEW_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                            CONSTRAINT PK_REVIEW PRIMARY KEY,

                        MEMBER_ID NUMBER NOT NULL,
                        PLACE_ID NUMBER NOT NULL,

                        REVIEW_TITLE VARCHAR2(200) NOT NULL,
                        REVIEW_CONTENT CLOB NOT NULL,

                        RATING NUMBER(2, 1) NOT NULL,

                        IMAGE_URL VARCHAR2(500),

                        VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,

                        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
                        UPDATED_AT DATE,

                        IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,

                        CONSTRAINT FK_REVIEW_MEMBER
                            FOREIGN KEY (MEMBER_ID)
                                REFERENCES MEMBER(MEMBER_ID),

                        CONSTRAINT FK_REVIEW_PLACE
                            FOREIGN KEY (PLACE_ID)
                                REFERENCES PLACES(PLACE_ID),

                        CONSTRAINT CK_REVIEW_RATING
                            CHECK (RATING BETWEEN 1.0 AND 5.0),

                        CONSTRAINT CK_REVIEW_VIEW_COUNT
                            CHECK (VIEW_COUNT >= 0),

                        CONSTRAINT CK_REVIEW_DELETED
                            CHECK (IS_DELETED IN ('Y', 'N'))
);

-- REVIEW_LIKE
-- 좋아요 수만 저장하면 누가 눌렀는지 확인할 수 없으므로 회원별 좋아요를 별도 저장
CREATE TABLE REVIEW_LIKE (
                             LIKE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                 CONSTRAINT PK_REVIEW_LIKE PRIMARY KEY,

                             REVIEW_ID NUMBER NOT NULL,
                             MEMBER_ID NUMBER NOT NULL,

                             CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

                             CONSTRAINT FK_REVIEW_LIKE_REVIEW
                                 FOREIGN KEY (REVIEW_ID)
                                     REFERENCES REVIEW(REVIEW_ID)
                                     ON DELETE CASCADE,

                             CONSTRAINT FK_REVIEW_LIKE_MEMBER
                                 FOREIGN KEY (MEMBER_ID)
                                     REFERENCES MEMBER(MEMBER_ID)
                                     ON DELETE CASCADE,

                             CONSTRAINT UK_REVIEW_LIKE
                                 UNIQUE (REVIEW_ID, MEMBER_ID)
);

-- REVIEW_COMMENT
CREATE TABLE REVIEW_COMMENT (
                                COMMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
                                    CONSTRAINT PK_REVIEW_COMMENT PRIMARY KEY,

                                REVIEW_ID NUMBER NOT NULL,
                                MEMBER_ID NUMBER NOT NULL,

                                CONTENT VARCHAR2(500) NOT NULL,

                                CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
                                UPDATED_AT DATE,

                                IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,

                                CONSTRAINT FK_COMMENT_REVIEW
                                    FOREIGN KEY (REVIEW_ID)
                                        REFERENCES REVIEW(REVIEW_ID)
                                        ON DELETE CASCADE,

                                CONSTRAINT FK_COMMENT_MEMBER
                                    FOREIGN KEY (MEMBER_ID)
                                        REFERENCES MEMBER(MEMBER_ID),

                                CONSTRAINT CK_COMMENT_DELETED
                                    CHECK (IS_DELETED IN ('Y', 'N'))
);

CREATE INDEX IDX_PAYMENT_MEMBER
    ON PAYMENT(MEMBER_ID);

CREATE INDEX IDX_SURVEY_MEMBER
    ON TRAVEL_SURVEY(MEMBER_ID);

CREATE INDEX IDX_ANSWER_SURVEY
    ON SURVEY_ANSWER(SURVEY_ID);

CREATE INDEX IDX_PLACES_REGION_CATEGORY
    ON PLACES(REGION, CATEGORY);

CREATE INDEX IDX_TYPE_PLACE_CODE
    ON TRAVEL_TYPE_PLACE(TRAVEL_CODE);

CREATE INDEX IDX_TYPE_PLACE_PLACE
    ON TRAVEL_TYPE_PLACE(PLACE_ID);

CREATE INDEX IDX_COURSE_MEMBER
    ON TRAVEL_COURSES(MEMBER_ID);

CREATE INDEX IDX_DETAILS_COURSE
    ON COURSE_DETAILS(COURSE_ID);

CREATE INDEX IDX_DETAILS_PLACE
    ON COURSE_DETAILS(PLACE_ID);

CREATE INDEX IDX_CHATBOT_MEMBER
    ON CHATBOT_HISTORY(MEMBER_ID);

CREATE INDEX IDX_CHATBOT_PAYMENT
    ON CHATBOT_HISTORY(PAYMENT_ID);

CREATE INDEX IDX_REVIEW_MEMBER
    ON REVIEW(MEMBER_ID);

CREATE INDEX IDX_REVIEW_PLACE
    ON REVIEW(PLACE_ID);

CREATE INDEX IDX_REVIEW_LIKE_MEMBER
    ON REVIEW_LIKE(MEMBER_ID);

CREATE INDEX IDX_COMMENT_REVIEW
    ON REVIEW_COMMENT(REVIEW_ID);

CREATE INDEX IDX_COMMENT_MEMBER
    ON REVIEW_COMMENT(MEMBER_ID);

-- 로컬 연동 확인용 테스트 회원: 같은 이메일이 이미 있으면 추가하지 않음
INSERT INTO MEMBER (
    EMAIL,
    PASSWORD,
    NAME,
    NICKNAME,
    PHONE
)
SELECT
    'test@test.com',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    '테스트회원',
    'testuser',
    '010-1111-2222'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM MEMBER
    WHERE EMAIL = 'test@test.com'
);

/* =========================
   MEMBER: 회원 정보
   ========================= */
COMMENT ON TABLE MEMBER IS '서비스 회원의 로그인, 프로필, 계정 상태 정보를 저장하는 테이블';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN MEMBER.EMAIL IS '회원 이메일, 로그인 ID로 사용 가능하며 중복 불가';
COMMENT ON COLUMN MEMBER.PASSWORD IS '회원 비밀번호, 실제 서비스에서는 암호화된 해시값 저장';
COMMENT ON COLUMN MEMBER.NAME IS '회원 실명 또는 이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '서비스에서 표시되는 회원 닉네임, 중복 불가';
COMMENT ON COLUMN MEMBER.PHONE IS '회원 연락처';
COMMENT ON COLUMN MEMBER.LOGIN_TYPE IS '로그인 유형, 기본값은 일반 로그인인 LOCAL';
COMMENT ON COLUMN MEMBER.STATUS IS '회원 상태, ACTIVE/WITHDRAWN 중 하나';
COMMENT ON COLUMN MEMBER.CREATED_AT IS '회원 가입 일시';
COMMENT ON COLUMN MEMBER.UPDATED_AT IS '회원 정보 마지막 수정 일시';

/* =========================
   TRAVEL_TYPE_MASTER: 여행 유형 마스터
   ========================= */
COMMENT ON TABLE TRAVEL_TYPE_MASTER IS '취향 검사 결과로 분류되는 여행 유형 코드와 설명을 관리하는 기준 테이블';
COMMENT ON COLUMN TRAVEL_TYPE_MASTER.TRAVEL_CODE IS '5글자 여행 유형 코드, 예: ATLSR';
COMMENT ON COLUMN TRAVEL_TYPE_MASTER.TYPE_TITLE IS '여행 유형 이름 또는 제목';
COMMENT ON COLUMN TRAVEL_TYPE_MASTER.TYPE_DESCRIPTION IS '여행 유형에 대한 상세 설명';
COMMENT ON COLUMN TRAVEL_TYPE_MASTER.IMAGE_URL IS '여행 유형을 대표하는 이미지 URL';

/* =========================
   SURVEY_QUESTION: 취향 검사 질문
   ========================= */
COMMENT ON TABLE SURVEY_QUESTION IS '여행 취향 검사를 구성하는 질문 정보를 저장하는 테이블';
COMMENT ON COLUMN SURVEY_QUESTION.QUESTION_ID IS '취향 검사 질문 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN SURVEY_QUESTION.QUESTION_TEXT IS '사용자에게 보여줄 질문 문구';
COMMENT ON COLUMN SURVEY_QUESTION.CATEGORY IS '질문 분류, 예: 여행성향/음식취향/문화취향 등';

/* =========================
   SURVEY_OPTION: 취향 검사 선택지
   ========================= */
COMMENT ON TABLE SURVEY_OPTION IS '각 취향 검사 질문에 연결되는 선택지와 점수 정보를 저장하는 테이블';
COMMENT ON COLUMN SURVEY_OPTION.OPTION_ID IS '선택지 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN SURVEY_OPTION.QUESTION_ID IS '선택지가 속한 질문 번호, SURVEY_QUESTION 참조';
COMMENT ON COLUMN SURVEY_OPTION.OPTION_TEXT IS '사용자에게 보여줄 선택지 문구';
COMMENT ON COLUMN SURVEY_OPTION.SCORE_CODE IS '선택지가 반영되는 여행 성향 코드 또는 점수 분류';
COMMENT ON COLUMN SURVEY_OPTION.SCORE_VALUE IS '선택지 선택 시 반영되는 점수 값';

/* =========================
   PLACES: 장소 정보
   ========================= */
COMMENT ON TABLE PLACES IS '관광지, 식당, 카페, 숙소 등 추천 가능한 장소 정보를 저장하는 테이블';
COMMENT ON COLUMN PLACES.PLACE_ID IS '장소 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN PLACES.API_PROVIDER IS '장소 정보를 가져온 API 제공처, 예: TOURAPI/KAKAO/NAVER';
COMMENT ON COLUMN PLACES.API_PLACE_ID IS '외부 API에서 제공하는 장소 고유 ID';
COMMENT ON COLUMN PLACES.CONTENT_ID IS 'TourAPI 등에서 제공하는 콘텐츠 ID';
COMMENT ON COLUMN PLACES.NAME IS '장소명';
COMMENT ON COLUMN PLACES.CATEGORY IS '장소 분류, TOUR/RESTAURANT/CAFE/HOTEL 중 하나';
COMMENT ON COLUMN PLACES.API_CATEGORY IS '외부 API에서 제공하는 원본 카테고리명';
COMMENT ON COLUMN PLACES.REGION IS '장소가 속한 지역명, 예: 서울 종로구';
COMMENT ON COLUMN PLACES.ADDRESS IS '지번 주소 또는 기본 주소';
COMMENT ON COLUMN PLACES.ROAD_ADDRESS IS '도로명 주소';
COMMENT ON COLUMN PLACES.LATITUDE IS '장소 위도 값';
COMMENT ON COLUMN PLACES.LONGITUDE IS '장소 경도 값';
COMMENT ON COLUMN PLACES.PHONE IS '장소 전화번호';
COMMENT ON COLUMN PLACES.PLACE_URL IS '장소 상세 페이지 또는 외부 링크';
COMMENT ON COLUMN PLACES.RATING IS '장소 평점, 0점 이상 5점 이하';
COMMENT ON COLUMN PLACES.REVIEW_COUNT IS '장소에 등록된 후기 수';
COMMENT ON COLUMN PLACES.DESCRIPTION IS '장소 상세 설명';
COMMENT ON COLUMN PLACES.IMAGE_URL IS '장소 대표 이미지 URL';
COMMENT ON COLUMN PLACES.TAG_HISTORY IS '역사/전통 분위기 태그 여부, Y/N';
COMMENT ON COLUMN PLACES.TAG_MODERN IS '현대적/트렌디한 분위기 태그 여부, Y/N';
COMMENT ON COLUMN PLACES.TAG_BUDGET IS '가성비 성향 태그 여부, Y/N';
COMMENT ON COLUMN PLACES.TAG_LUXURY IS '고급/럭셔리 성향 태그 여부, Y/N';
COMMENT ON COLUMN PLACES.TAG_STABLE IS '차분하고 안정적인 코스 성향 태그 여부, Y/N';
COMMENT ON COLUMN PLACES.TAG_DOPAMINE IS '자극적이고 활동적인 코스 성향 태그 여부, Y/N';
COMMENT ON COLUMN PLACES.TAG_RELAX IS '휴식/힐링 성향 태그 여부, Y/N';
COMMENT ON COLUMN PLACES.TAG_PACKED IS '빽빽한 일정 또는 알찬 코스 성향 태그 여부, Y/N';
COMMENT ON COLUMN PLACES.IS_ACTIVE IS '장소 사용 여부, Y이면 추천 가능';
COMMENT ON COLUMN PLACES.CREATED_AT IS '장소 데이터 등록 일시';
COMMENT ON COLUMN PLACES.UPDATED_AT IS '장소 데이터 마지막 수정 일시';

/* =========================
   PAYMENT: 결제 정보
   ========================= */
COMMENT ON TABLE PAYMENT IS '유료 챗봇 이용권 결제 내역과 남은 이용 횟수를 관리하는 테이블';
COMMENT ON COLUMN PAYMENT.PAYMENT_ID IS '결제 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN PAYMENT.MEMBER_ID IS '결제한 회원 번호, MEMBER 참조';
COMMENT ON COLUMN PAYMENT.PRODUCT_NAME IS '결제 상품명, 예: 유료 챗봇 1회권/30일권';
COMMENT ON COLUMN PAYMENT.AMOUNT IS '결제 금액';
COMMENT ON COLUMN PAYMENT.PAYMENT_METHOD IS '결제 수단, 예: 카드/카카오페이/토스페이';
COMMENT ON COLUMN PAYMENT.PAYMENT_PROVIDER IS '결제 API 제공사, 예: TOSS/KAKAO/DANAL';
COMMENT ON COLUMN PAYMENT.ORDER_ID IS '서비스 내부 주문 번호, 중복 불가';
COMMENT ON COLUMN PAYMENT.PAYMENT_KEY IS '결제 승인 후 PG사에서 제공하는 결제 키';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS IS '결제 상태, READY/PAID/CANCELED/FAILED 중 하나';
COMMENT ON COLUMN PAYMENT.REMAIN_COUNT IS '결제 상품으로 사용할 수 있는 남은 챗봇 이용 횟수';
COMMENT ON COLUMN PAYMENT.EXPIRED_AT IS '이용권 만료 일시';
COMMENT ON COLUMN PAYMENT.PAID_AT IS '결제 승인 일시';
COMMENT ON COLUMN PAYMENT.CANCELED_AT IS '결제 취소 일시';
COMMENT ON COLUMN PAYMENT.FAIL_REASON IS '결제 실패 또는 취소 사유';
COMMENT ON COLUMN PAYMENT.CREATED_AT IS '결제 요청 생성 일시';

/* =========================
   TRAVEL_SURVEY: 여행 취향 검사 실행 기록
   ========================= */
COMMENT ON TABLE TRAVEL_SURVEY IS '사용자가 여행 취향 검사를 진행한 기록과 기본 여행 조건을 저장하는 테이블';
COMMENT ON COLUMN TRAVEL_SURVEY.SURVEY_ID IS '취향 검사 실행 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN TRAVEL_SURVEY.MEMBER_ID IS '검사를 진행한 회원 번호, 비회원 검사를 허용하면 NULL 가능';
COMMENT ON COLUMN TRAVEL_SURVEY.GUEST_TOKEN IS '비회원 검사 결과를 회원가입 후 연결하기 위한 임시 토큰';
COMMENT ON COLUMN TRAVEL_SURVEY.REGION IS '사용자가 선택한 여행 지역';
COMMENT ON COLUMN TRAVEL_SURVEY.START_DATE IS '여행 시작일';
COMMENT ON COLUMN TRAVEL_SURVEY.END_DATE IS '여행 종료일';
COMMENT ON COLUMN TRAVEL_SURVEY.PEOPLE_COUNT IS '여행 인원 수';
COMMENT ON COLUMN TRAVEL_SURVEY.CREATED_AT IS '취향 검사 생성 일시';

/* =========================
   SURVEY_ANSWER: 취향 검사 답변
   ========================= */
COMMENT ON TABLE SURVEY_ANSWER IS '사용자가 취향 검사에서 선택한 질문별 답변을 저장하는 테이블';
COMMENT ON COLUMN SURVEY_ANSWER.ANSWER_ID IS '답변 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN SURVEY_ANSWER.SURVEY_ID IS '답변이 속한 취향 검사 실행 번호';
COMMENT ON COLUMN SURVEY_ANSWER.QUESTION_ID IS '사용자가 답변한 질문 번호';
COMMENT ON COLUMN SURVEY_ANSWER.OPTION_ID IS '사용자가 선택한 선택지 번호';

/* =========================
   TRAVEL_TYPE_PLACE: 여행 유형별 장소 매핑
   ========================= */
COMMENT ON TABLE TRAVEL_TYPE_PLACE IS '여행 유형과 장소를 연결하고 추천 가중치를 관리하는 매핑 테이블';
COMMENT ON COLUMN TRAVEL_TYPE_PLACE.TYPE_PLACE_ID IS '여행 유형-장소 매핑 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN TRAVEL_TYPE_PLACE.TRAVEL_CODE IS '여행 유형 코드, TRAVEL_TYPE_MASTER 참조';
COMMENT ON COLUMN TRAVEL_TYPE_PLACE.PLACE_ID IS '추천 장소 번호, PLACES 참조';
COMMENT ON COLUMN TRAVEL_TYPE_PLACE.WEIGHT_SCORE IS '해당 여행 유형에서 장소를 추천할 때 적용할 가중치 점수';

/* =========================
   SURVEY_RESULT: 취향 검사 결과
   ========================= */
COMMENT ON TABLE SURVEY_RESULT IS '취향 검사 결과로 산출된 여행 유형과 날씨 정보를 저장하는 테이블';
COMMENT ON COLUMN SURVEY_RESULT.RESULT_ID IS '취향 검사 결과 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN SURVEY_RESULT.SURVEY_ID IS '결과가 연결된 취향 검사 실행 번호';
COMMENT ON COLUMN SURVEY_RESULT.TRAVEL_CODE IS '검사 결과로 결정된 여행 유형 코드';
COMMENT ON COLUMN SURVEY_RESULT.WEATHER_STATUS IS '추천 시점의 날씨 상태';
COMMENT ON COLUMN SURVEY_RESULT.TEMPERATURE IS '추천 시점의 기온';
COMMENT ON COLUMN SURVEY_RESULT.RAIN_PROBABILITY IS '추천 시점의 강수 확률, 0~100';
COMMENT ON COLUMN SURVEY_RESULT.CREATED_AT IS '검사 결과 생성 일시';

/* =========================
   TRAVEL_COURSES: 여행 코스
   ========================= */
COMMENT ON TABLE TRAVEL_COURSES IS '취향 검사 또는 챗봇을 통해 생성된 여행 코스의 기본 정보를 저장하는 테이블';
COMMENT ON COLUMN TRAVEL_COURSES.COURSE_ID IS '여행 코스 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN TRAVEL_COURSES.MEMBER_ID IS '코스를 생성하거나 소유한 회원 번호';
COMMENT ON COLUMN TRAVEL_COURSES.RESULT_ID IS '취향 검사 결과 기반 코스인 경우 연결되는 결과 번호';
COMMENT ON COLUMN TRAVEL_COURSES.PAYMENT_ID IS '유료 챗봇으로 생성된 코스인 경우 연결되는 결제 번호';
COMMENT ON COLUMN TRAVEL_COURSES.TITLE IS '여행 코스 제목';
COMMENT ON COLUMN TRAVEL_COURSES.DESCRIPTION IS '여행 코스 설명';
COMMENT ON COLUMN TRAVEL_COURSES.TRAVEL_CODE IS '코스에 연결된 여행 유형 코드';
COMMENT ON COLUMN TRAVEL_COURSES.COURSE_TYPE IS '코스 생성 방식, CUSTOM/SURVEY/CHATBOT 중 하나';
COMMENT ON COLUMN TRAVEL_COURSES.REGION IS '코스의 주요 여행 지역';
COMMENT ON COLUMN TRAVEL_COURSES.IS_PUBLIC IS '코스 공개 여부, Y/N';
COMMENT ON COLUMN TRAVEL_COURSES.VIEW_COUNT IS '코스 조회 수';
COMMENT ON COLUMN TRAVEL_COURSES.TOTAL_DISTANCE_KM IS '코스 전체 이동거리 합계, km 단위';
COMMENT ON COLUMN TRAVEL_COURSES.TOTAL_TRAVEL_MINUTES IS '코스 전체 이동시간 합계, 분 단위';
COMMENT ON COLUMN TRAVEL_COURSES.TOTAL_VISIT_MINUTES IS '코스 전체 예상 방문시간 합계, 분 단위';
COMMENT ON COLUMN TRAVEL_COURSES.TOTAL_COURSE_MINUTES IS '이동시간과 예상 방문시간을 합한 전체 코스시간, 분 단위';
COMMENT ON COLUMN TRAVEL_COURSES.CREATED_AT IS '코스 생성 일시';
COMMENT ON COLUMN TRAVEL_COURSES.UPDATED_AT IS '코스 마지막 수정 일시';

/* =========================
   COURSE_DETAILS: 여행 코스 상세 장소
   ========================= */
COMMENT ON TABLE COURSE_DETAILS IS '여행 코스에 포함되는 장소의 방문 순서, 일정, 메모를 저장하는 테이블';
COMMENT ON COLUMN COURSE_DETAILS.DETAIL_ID IS '코스 상세 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN COURSE_DETAILS.COURSE_ID IS '상세 장소가 속한 여행 코스 번호';
COMMENT ON COLUMN COURSE_DETAILS.PLACE_ID IS '코스에 포함된 장소 번호';
COMMENT ON COLUMN COURSE_DETAILS.DAY_NO IS '여행 며칠 차인지 나타내는 번호';
COMMENT ON COLUMN COURSE_DETAILS.PLACE_ORDER IS '같은 날짜 안에서의 장소 방문 순서';
COMMENT ON COLUMN COURSE_DETAILS.MEMO IS '장소별 코스 메모';
COMMENT ON COLUMN COURSE_DETAILS.VISIT_TIME IS '권장 방문 시간 또는 일정 시간대';
COMMENT ON COLUMN COURSE_DETAILS.STAY_MINUTES IS '권장 체류 시간, 분 단위';
COMMENT ON COLUMN COURSE_DETAILS.VISIT_DATE IS '해당 장소를 방문할 날짜';
COMMENT ON COLUMN COURSE_DETAILS.DISTANCE_FROM_PREV_KM IS '직전 장소로부터의 이동거리, km 단위';
COMMENT ON COLUMN COURSE_DETAILS.TRAVEL_MINUTES_FROM_PREV IS '직전 장소로부터의 이동시간, 분 단위';
COMMENT ON COLUMN COURSE_DETAILS.CREATED_AT IS '코스 상세 등록 일시';

/* =========================
   CHATBOT_HISTORY: 유료 챗봇 이용 기록
   ========================= */
COMMENT ON TABLE CHATBOT_HISTORY IS '유료 챗봇 질문, 답변, 추천 코스 생성 기록을 저장하는 테이블';
COMMENT ON COLUMN CHATBOT_HISTORY.CHAT_ID IS '챗봇 이용 기록 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN CHATBOT_HISTORY.MEMBER_ID IS '챗봇을 이용한 회원 번호';
COMMENT ON COLUMN CHATBOT_HISTORY.PAYMENT_ID IS '챗봇 이용권 결제 번호';
COMMENT ON COLUMN CHATBOT_HISTORY.RESULT_ID IS '챗봇 답변과 연결된 취향 검사 결과 번호';
COMMENT ON COLUMN CHATBOT_HISTORY.COURSE_ID IS '챗봇 답변으로 생성된 여행 코스 번호';
COMMENT ON COLUMN CHATBOT_HISTORY.QUESTION IS '사용자가 챗봇에 입력한 질문 내용';
COMMENT ON COLUMN CHATBOT_HISTORY.TRAVEL_CONCEPT IS '사용자가 요청한 여행 컨셉, 예: 야경/드라이브/도서관 투어';
COMMENT ON COLUMN CHATBOT_HISTORY.ANSWER IS '챗봇이 생성한 답변 내용';
COMMENT ON COLUMN CHATBOT_HISTORY.COURSE_SUMMARY IS '챗봇이 추천한 코스 요약';
COMMENT ON COLUMN CHATBOT_HISTORY.CREATED_AT IS '챗봇 이용 기록 생성 일시';

/* =========================
   REVIEW: 방문 후기
   ========================= */
COMMENT ON TABLE REVIEW IS '회원이 장소에 대해 작성한 방문 후기 게시글을 저장하는 테이블';
COMMENT ON COLUMN REVIEW.REVIEW_ID IS '후기 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN REVIEW.MEMBER_ID IS '후기를 작성한 회원 번호';
COMMENT ON COLUMN REVIEW.PLACE_ID IS '후기 대상 장소 번호';
COMMENT ON COLUMN REVIEW.REVIEW_TITLE IS '후기 제목';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '후기 본문 내용';
COMMENT ON COLUMN REVIEW.RATING IS '회원이 부여한 평점, 1.0~5.0';
COMMENT ON COLUMN REVIEW.IMAGE_URL IS '후기에 첨부된 대표 이미지 URL';
COMMENT ON COLUMN REVIEW.VIEW_COUNT IS '후기 조회 수';
COMMENT ON COLUMN REVIEW.CREATED_AT IS '후기 작성 일시';
COMMENT ON COLUMN REVIEW.UPDATED_AT IS '후기 마지막 수정 일시';
COMMENT ON COLUMN REVIEW.IS_DELETED IS '후기 논리 삭제 여부, Y/N';

/* =========================
   REVIEW_LIKE: 후기 좋아요
   ========================= */
COMMENT ON TABLE REVIEW_LIKE IS '회원이 방문 후기에 누른 좋아요 정보를 저장하는 테이블';
COMMENT ON COLUMN REVIEW_LIKE.LIKE_ID IS '좋아요 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN REVIEW_LIKE.REVIEW_ID IS '좋아요를 누른 후기 번호';
COMMENT ON COLUMN REVIEW_LIKE.MEMBER_ID IS '좋아요를 누른 회원 번호';
COMMENT ON COLUMN REVIEW_LIKE.CREATED_AT IS '좋아요를 누른 일시';

/* =========================
   REVIEW_COMMENT: 후기 댓글
   ========================= */
COMMENT ON TABLE REVIEW_COMMENT IS '방문 후기 게시글에 달린 댓글 정보를 저장하는 테이블';
COMMENT ON COLUMN REVIEW_COMMENT.COMMENT_ID IS '댓글 고유 번호, 자동 증가 기본키';
COMMENT ON COLUMN REVIEW_COMMENT.REVIEW_ID IS '댓글이 달린 후기 번호';
COMMENT ON COLUMN REVIEW_COMMENT.MEMBER_ID IS '댓글을 작성한 회원 번호';
COMMENT ON COLUMN REVIEW_COMMENT.CONTENT IS '댓글 내용';
COMMENT ON COLUMN REVIEW_COMMENT.CREATED_AT IS '댓글 작성 일시';
COMMENT ON COLUMN REVIEW_COMMENT.UPDATED_AT IS '댓글 마지막 수정 일시';
COMMENT ON COLUMN REVIEW_COMMENT.IS_DELETED IS '댓글 논리 삭제 여부, Y/N';

COMMIT;
