package com.seoulink.backend.domain.course.dto.response;

public record CourseBuilderPlaceResponse(
        Long placeId,
        String apiProvider,
        String apiPlaceId,
        Long contentId,
        String name,
        String category,
        String apiCategory,
        String theme,
        String region,
        String address,
        String roadAddress,
        Double latitude,
        Double longitude,
        String phone,
        String placeUrl,
        Double rating,
        Integer reviewCount,
        String description,
        String imageUrl,
        String tagHistory,
        String tagModern,
        String tagBudget,
        String tagLuxury,
        String tagStable,
        String tagDopamine,
        String tagRelax,
        String tagPacked,
        String sourceType,
        String recommendYn,
        String approvalStatus,
        String indoorYn,
        String rainOkYn,
        String nightOkYn,
        Integer avgStayMinutes,
        String priceLevel,
        String dataSource
) {

    /**
     * PlaceColumnSearchService에서 사용하는 생성자입니다.
     * PLACES의 추천/분류 컬럼까지 모두 응답합니다.
     */
    public CourseBuilderPlaceResponse(
            Long placeId,
            String apiProvider,
            String apiPlaceId,
            String name,
            String category,
            String apiCategory,
            String region,
            String address,
            String roadAddress,
            Double latitude,
            Double longitude,
            String phone,
            String placeUrl,
            Double rating,
            Integer reviewCount,
            String description,
            String imageUrl,
            String tagHistory,
            String tagModern,
            String tagBudget,
            String tagLuxury,
            String tagStable,
            String tagDopamine,
            String tagRelax,
            String tagPacked,
            String sourceType,
            String recommendYn,
            String approvalStatus,
            String indoorYn,
            String rainOkYn,
            String nightOkYn,
            Integer avgStayMinutes,
            String priceLevel
    ) {
        this(
                placeId,
                apiProvider,
                apiPlaceId,
                null,
                name,
                category,
                apiCategory,
                null,
                region,
                address,
                roadAddress,
                latitude,
                longitude,
                phone,
                placeUrl,
                rating,
                reviewCount,
                description,
                imageUrl,
                tagHistory,
                tagModern,
                tagBudget,
                tagLuxury,
                tagStable,
                tagDopamine,
                tagRelax,
                tagPacked,
                sourceType,
                recommendYn,
                approvalStatus,
                indoorYn,
                rainOkYn,
                nightOkYn,
                avgStayMinutes,
                priceLevel,
                "DB"
        );
    }

    /**
     * CourseBuilderService 최신 버전에서 사용하는 생성자입니다.
     * contentId, theme, indoorYn, dataSource를 포함합니다.
     */
    public CourseBuilderPlaceResponse(
            Long placeId,
            String apiProvider,
            String apiPlaceId,
            Long contentId,
            String name,
            String category,
            String apiCategory,
            String theme,
            String region,
            String address,
            String roadAddress,
            Double latitude,
            Double longitude,
            String phone,
            String placeUrl,
            Double rating,
            Integer reviewCount,
            String description,
            String imageUrl,
            String indoorYn,
            String sourceType,
            String recommendYn,
            String approvalStatus,
            String dataSource
    ) {
        this(
                placeId,
                apiProvider,
                apiPlaceId,
                contentId,
                name,
                category,
                apiCategory,
                theme,
                region,
                address,
                roadAddress,
                latitude,
                longitude,
                phone,
                placeUrl,
                rating,
                reviewCount,
                description,
                imageUrl,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                sourceType,
                recommendYn,
                approvalStatus,
                indoorYn,
                null,
                null,
                null,
                null,
                dataSource
        );
    }

    /**
     * CourseBuilderService 예전 버전에서 사용하는 생성자입니다.
     * indoorYn이 없는 버전과도 호환됩니다.
     */
    public CourseBuilderPlaceResponse(
            Long placeId,
            String apiProvider,
            String apiPlaceId,
            Long contentId,
            String name,
            String category,
            String apiCategory,
            String theme,
            String region,
            String address,
            String roadAddress,
            Double latitude,
            Double longitude,
            String phone,
            String placeUrl,
            Double rating,
            Integer reviewCount,
            String description,
            String imageUrl,
            String sourceType,
            String recommendYn,
            String approvalStatus,
            String dataSource
    ) {
        this(
                placeId,
                apiProvider,
                apiPlaceId,
                contentId,
                name,
                category,
                apiCategory,
                theme,
                region,
                address,
                roadAddress,
                latitude,
                longitude,
                phone,
                placeUrl,
                rating,
                reviewCount,
                description,
                imageUrl,
                null,
                sourceType,
                recommendYn,
                approvalStatus,
                dataSource
        );
    }
}
