-- Development reset only: deletes all SeoulLink tables.
DECLARE
  TYPE table_name_list IS TABLE OF VARCHAR2(30);
  table_names table_name_list := table_name_list('REVIEW_COMMENT','REVIEW_LIKE','REVIEW_TAG','REVIEW_IMAGE','REVIEW','CHATBOT_HISTORY','COURSE_DETAILS','TRAVEL_COURSES','SURVEY_RESULT','TRAVEL_TYPE_PLACE','SURVEY_ANSWER','TRAVEL_SURVEY','PAYMENT','PLACES','SURVEY_OPTION','SURVEY_QUESTION','TRAVEL_TYPE_MASTER','MEMBER');
BEGIN
  FOR i IN 1..table_names.COUNT LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE ' || table_names(i) || ' CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
  END LOOP;
END;
