-- MEMBER
-- seoul-link-back(52) database/seoulink.sql 기준
CREATE TABLE MEMBER (
    MEMBER_ID NUMBER GENERATED ALWAYS AS IDENTITY
        CONSTRAINT PK_MEMBER PRIMARY KEY,

    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    NICKNAME VARCHAR2(50),
    PHONE VARCHAR2(20),

    SOCIAL_PROVIDER VARCHAR2(30),
    SOCIAL_ID VARCHAR2(100),

    LOGIN_TYPE VARCHAR2(20) DEFAULT 'LOCAL' NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_MEMBER_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT UK_MEMBER_SOCIAL UNIQUE (SOCIAL_PROVIDER, SOCIAL_ID),

    CONSTRAINT CK_MEMBER_LOGIN_TYPE
        CHECK (LOGIN_TYPE IN ('LOCAL', 'SOCIAL')),

    CONSTRAINT CK_MEMBER_SOCIAL_PROVIDER
        CHECK (
            SOCIAL_PROVIDER IS NULL
            OR SOCIAL_PROVIDER IN ('GOOGLE', 'NAVER', 'KAKAO')
        ),

    CONSTRAINT CK_MEMBER_LOGIN_RULE
        CHECK (
            (
                LOGIN_TYPE = 'LOCAL'
                AND SOCIAL_PROVIDER IS NULL
                AND SOCIAL_ID IS NULL
            )
            OR
            (
                LOGIN_TYPE = 'SOCIAL'
                AND SOCIAL_PROVIDER IS NOT NULL
                AND SOCIAL_ID IS NOT NULL
            )
        ),

    CONSTRAINT CK_MEMBER_STATUS
        CHECK (STATUS IN ('ACTIVE', 'WITHDRAWN'))
);
