-- PLACES
CREATE TABLE PLACES (
    PLACE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_PLACES PRIMARY KEY,

    /* 외부 API 정보 */
    API_PROVIDER VARCHAR2(30) NOT NULL,
    API_PLACE_ID VARCHAR2(100) NOT NULL,
    CONTENT_ID NUMBER,

    /* 장소 기본 정보 */
    NAME VARCHAR2(200) NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,
    API_CATEGORY VARCHAR2(200),

    REGION VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(500) NOT NULL,
    ROAD_ADDRESS VARCHAR2(500),

    LATITUDE NUMBER(10, 7) NOT NULL,
    LONGITUDE NUMBER(10, 7) NOT NULL,

    PHONE VARCHAR2(50),
    PLACE_URL VARCHAR2(1000),

    /* 평점 및 리뷰 */
    RATING NUMBER(3, 2)
        DEFAULT 0.0
        NOT NULL,

    REVIEW_COUNT NUMBER
        DEFAULT 0
        NOT NULL,

    DESCRIPTION CLOB,

    /* 대표 이미지 */
    IMAGE_URL VARCHAR2(1000),

    IMAGE_SOURCE VARCHAR2(30),

    IMAGE_MATCH_SCORE NUMBER(3),

    IMAGE_STATUS VARCHAR2(20)
        DEFAULT 'NOT_FOUND'
        NOT NULL,

    /* 이미지 라이선스 및 출처 표시 */
    IMAGE_LICENSE_TYPE VARCHAR2(30),

    IMAGE_ATTRIBUTION VARCHAR2(500),

    /* 여행 취향 추천 태그 */
    TAG_HISTORY CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    TAG_MODERN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    TAG_BUDGET CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    TAG_LUXURY CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    TAG_STABLE CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    TAG_DOPAMINE CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    TAG_RELAX CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    TAG_PACKED CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    /* 지도 코스 만들기 테마 */
    THEME_PALACE_CULTURE_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    THEME_NATURE_HANGANG_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    THEME_DATE_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    THEME_FOOD_TOUR_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    THEME_CAFE_TOUR_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    THEME_SHOPPING_HOTPLACE_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    THEME_NIGHT_VIEW_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    THEME_HOTEL_STAY_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    /* 장소 데이터 관리 정보 */
    SOURCE_TYPE VARCHAR2(20)
        DEFAULT 'RECOMMEND'
        NOT NULL,

    RECOMMEND_YN CHAR(1)
        DEFAULT 'Y'
        NOT NULL,

    APPROVAL_STATUS VARCHAR2(20)
        DEFAULT 'APPROVED'
        NOT NULL,

    CREATED_BY_MEMBER_ID NUMBER,

    /* 장소 환경 정보 */
    INDOOR_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    RAIN_OK_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    NIGHT_OK_YN CHAR(1)
        DEFAULT 'N'
        NOT NULL,

    AVG_STAY_MINUTES NUMBER
        DEFAULT 60
        NOT NULL,

    PRICE_LEVEL VARCHAR2(20)
        DEFAULT 'MEDIUM'
        NOT NULL,

    IS_ACTIVE CHAR(1)
        DEFAULT 'Y'
        NOT NULL,

    CREATED_AT DATE
        DEFAULT SYSDATE
        NOT NULL,

    UPDATED_AT DATE
        DEFAULT SYSDATE
        NOT NULL,

    /* 외부 API 장소 중복 방지 */
    CONSTRAINT UK_PLACES_API
        UNIQUE (
            API_PROVIDER,
            API_PLACE_ID
        ),

    /* 장소를 최초 등록한 회원 */
    CONSTRAINT FK_PLACES_CREATED_BY
        FOREIGN KEY (CREATED_BY_MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
        ON DELETE SET NULL,

    /* 장소 카테고리 */
    CONSTRAINT CK_PLACES_CATEGORY
        CHECK (
            CATEGORY IN (
                'TOUR',
                'RESTAURANT',
                'CAFE',
                'HOTEL'
            )
        ),

    /* 평점 */
    CONSTRAINT CK_PLACES_RATING
        CHECK (
            RATING BETWEEN 0 AND 5
        ),

    /* 리뷰 수 */
    CONSTRAINT CK_PLACES_REVIEW_COUNT
        CHECK (
            REVIEW_COUNT >= 0
        ),

    /* 위도 */
    CONSTRAINT CK_PLACES_LATITUDE
        CHECK (
            LATITUDE BETWEEN -90 AND 90
        ),

    /* 경도 */
    CONSTRAINT CK_PLACES_LONGITUDE
        CHECK (
            LONGITUDE BETWEEN -180 AND 180
        ),

    /* 이미지 출처 */
    CONSTRAINT CK_PLACES_IMAGE_SOURCE
        CHECK (
            IMAGE_SOURCE IS NULL
            OR IMAGE_SOURCE IN (
                'TOURAPI',
                'PHOTO_KOREA',
                'WIKIMEDIA',
                'OFFICIAL_PERMISSION',
                'OWN_PHOTO',
                'REVIEW',
                'MANUAL'
            )
        ),

    /* 이미지 매칭 점수 */
    CONSTRAINT CK_PLACES_IMAGE_SCORE
        CHECK (
            IMAGE_MATCH_SCORE IS NULL
            OR IMAGE_MATCH_SCORE BETWEEN 0 AND 100
        ),

    /* 이미지 상태 */
    CONSTRAINT CK_PLACES_IMAGE_STATUS
        CHECK (
            IMAGE_STATUS IN (
                'APPROVED',
                'PENDING',
                'REJECTED',
                'NOT_FOUND'
            )
        ),

    /* 승인 또는 검수 중인 이미지는 URL 필수 */
    CONSTRAINT CK_PLACES_IMAGE_REQUIRED
        CHECK (
            IMAGE_STATUS IN (
                'REJECTED',
                'NOT_FOUND'
            )
            OR IMAGE_URL IS NOT NULL
        ),

    /* 이미지 라이선스 */
    CONSTRAINT CK_PLACES_IMAGE_LICENSE
        CHECK (
            IMAGE_LICENSE_TYPE IS NULL
            OR IMAGE_LICENSE_TYPE IN (
                'KOGL_TYPE1',
                'KOGL_TYPE2',
                'KOGL_TYPE3',
                'KOGL_TYPE4',
                'CC_BY_4_0',
                'CC_BY_SA_4_0',
                'DIRECT_PERMISSION',
                'OWN_PHOTO',
                'UNKNOWN'
            )
        ),

    /* 여행 취향 태그 */
    CONSTRAINT CK_PLACES_HISTORY
        CHECK (
            TAG_HISTORY IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_MODERN
        CHECK (
            TAG_MODERN IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_BUDGET
        CHECK (
            TAG_BUDGET IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_LUXURY
        CHECK (
            TAG_LUXURY IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_STABLE
        CHECK (
            TAG_STABLE IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_DOPAMINE
        CHECK (
            TAG_DOPAMINE IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_RELAX
        CHECK (
            TAG_RELAX IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_PACKED
        CHECK (
            TAG_PACKED IN ('Y', 'N')
        ),

    /* 지도 코스 테마 */
    CONSTRAINT CK_PLACES_THEME_PALACE
        CHECK (
            THEME_PALACE_CULTURE_YN IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_THEME_NATURE
        CHECK (
            THEME_NATURE_HANGANG_YN IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_THEME_DATE
        CHECK (
            THEME_DATE_YN IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_THEME_FOOD
        CHECK (
            THEME_FOOD_TOUR_YN IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_THEME_CAFE
        CHECK (
            THEME_CAFE_TOUR_YN IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_THEME_SHOP
        CHECK (
            THEME_SHOPPING_HOTPLACE_YN IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_THEME_NIGHT
        CHECK (
            THEME_NIGHT_VIEW_YN IN ('Y', 'N')
        ),

    CONSTRAINT CK_PLACES_THEME_HOTEL
        CHECK (
            THEME_HOTEL_STAY_YN IN ('Y', 'N')
        ),

    /* 데이터 출처 */
    CONSTRAINT CK_PLACES_SOURCE_TYPE
        CHECK (
            SOURCE_TYPE IN (
                'RECOMMEND',
                'USER_SELECTED',
                'API_IMPORTED'
            )
        ),

    /* 자동 추천 사용 여부 */
    CONSTRAINT CK_PLACES_RECOMMEND_YN
        CHECK (
            RECOMMEND_YN IN ('Y', 'N')
        ),

    /* 장소 검수 상태 */
    CONSTRAINT CK_PLACES_APPROVAL_STATUS
        CHECK (
            APPROVAL_STATUS IN (
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        ),

    /* 실내 여부 */
    CONSTRAINT CK_PLACES_INDOOR
        CHECK (
            INDOOR_YN IN ('Y', 'N')
        ),

    /* 비 오는 날 추천 여부 */
    CONSTRAINT CK_PLACES_RAIN_OK
        CHECK (
            RAIN_OK_YN IN ('Y', 'N')
        ),

    /* 야간 방문 가능 여부 */
    CONSTRAINT CK_PLACES_NIGHT_OK
        CHECK (
            NIGHT_OK_YN IN ('Y', 'N')
        ),

    /* 평균 체류 시간 */
    CONSTRAINT CK_PLACES_AVG_STAY
        CHECK (
            AVG_STAY_MINUTES >= 0
        ),

    /* 가격대 */
    CONSTRAINT CK_PLACES_PRICE_LEVEL
        CHECK (
            PRICE_LEVEL IN (
                'LOW',
                'MEDIUM',
                'HIGH'
            )
        ),

    /* 사용 여부 */
    CONSTRAINT CK_PLACES_ACTIVE
        CHECK (
            IS_ACTIVE IN ('Y', 'N')
        )
);

SELECT * FROM PLACES;
