-- PAYMENT
CREATE TABLE PAYMENT (
    /* 결제 1건의 상품, 금액, PG 승인 정보와 이용권 상태를 관리한다. */
    /* 결제 행을 구분하는 자동 증가 기본키 */
    PAYMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_PAYMENT PRIMARY KEY,

    /* 결제를 요청한 회원 번호(MEMBER 참조) */
    MEMBER_ID NUMBER NOT NULL,

    /* 서버가 금액 기준으로 결정한 이용권 또는 상품 이름 */
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    /* 실제 결제 금액(원) */
    AMOUNT NUMBER(10, 0) DEFAULT 0 NOT NULL,

    /* 사용자가 선택한 결제 수단(예: 카드, 간편결제) */
    PAYMENT_METHOD VARCHAR2(30) NOT NULL,
    /* 결제를 처리한 PG사 또는 결제 제공사(예: TOSS) */
    PAYMENT_PROVIDER VARCHAR2(30),

    /* 서비스에서 생성한 중복 불가 주문 식별자 */
    ORDER_ID VARCHAR2(100) NOT NULL,
    /* 결제 승인 후 PG사가 발급하는 거래 식별 키 */
    PAYMENT_KEY VARCHAR2(200),

    /* 결제 진행 상태: READY, PAID, CANCELED, FAILED */
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'READY' NOT NULL,

    /* 이용권에서 남은 사용 가능 횟수 */
    /* 이용권을 사용할 수 있는 마지막 일시 */
    EXPIRED_AT DATE,

    /* 결제가 승인되어 PAID 상태가 된 일시 */
    PAID_AT DATE,
    /* 결제가 취소된 일시 */
    CANCELED_AT DATE,
    /* 승인 실패 또는 취소 사유 */
    FAIL_REASON VARCHAR2(500),

    /* 결제 요청 행을 처음 생성한 일시 */
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_PAYMENT_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),

    CONSTRAINT UK_PAYMENT_ORDER
        UNIQUE (ORDER_ID),

    CONSTRAINT UK_PAYMENT_KEY
        UNIQUE (PAYMENT_KEY),

    CONSTRAINT CK_PAYMENT_AMOUNT
        CHECK (AMOUNT >= 0),

    CONSTRAINT CK_PAYMENT_STATUS
        CHECK (PAYMENT_STATUS IN ('READY', 'PAID', 'CANCELED', 'FAILED'))
);
