-- REVIEW
CREATE TABLE REVIEW (
    /* 회원이 장소를 방문한 뒤 작성하는 후기의 본문, 평점, 방문 정보와 대표 사진을 저장한다. */
    /* 후기 게시글을 구분하는 자동 증가 기본키 */
    REVIEW_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REVIEW PRIMARY KEY,

    /* 후기를 작성한 회원 번호(MEMBER 참조) */
    MEMBER_ID NUMBER NOT NULL,
    /* 후기 대상 장소 번호(PLACES 참조) */
    PLACE_ID NUMBER NOT NULL,
    /* 후기가 연결된 여행 코스 번호(TRAVEL_COURSES 참조, 선택값) */
    COURSE_ID NUMBER,

    /* 작성자가 실제로 장소를 방문한 날짜 */
    VISIT_DATE DATE,
    /* 혼자, 친구, 연인, 가족 등 함께 방문한 동행 유형 */
    COMPANION VARCHAR2(30) DEFAULT '혼자' NOT NULL,

    /* 후기 목록과 상세 화면에 표시할 제목 */
    REVIEW_TITLE VARCHAR2(200) NOT NULL,
    /* 후기 본문 전체 내용 */
    REVIEW_CONTENT CLOB NOT NULL,

    /* 방문 만족도 평점(0.0점부터 5.0점까지) */
    RATING NUMBER(2, 1) NOT NULL,

    /* 후기 목록 카드에 사용할 대표 사진 주소 */
    IMAGE_URL VARCHAR2(500),

    /* 후기 상세 페이지 조회 횟수 */
    VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,

    /* 후기를 처음 작성한 일시 */
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    /* 후기를 마지막으로 수정한 일시 */
    UPDATED_AT DATE,

    /* 실제 삭제 대신 숨김 처리 여부(Y/N) */
    IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,

    CONSTRAINT FK_REVIEW_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),

    CONSTRAINT FK_REVIEW_PLACE
        FOREIGN KEY (PLACE_ID)
        REFERENCES PLACES(PLACE_ID),

    CONSTRAINT FK_REVIEW_COURSE
        FOREIGN KEY (COURSE_ID)
        REFERENCES TRAVEL_COURSES(COURSE_ID),

    CONSTRAINT CK_REVIEW_RATING
        CHECK (RATING BETWEEN 0.0 AND 5.0),

    CONSTRAINT CK_REVIEW_COMPANION
        CHECK (COMPANION IN ('혼자', '연인', '친구', '가족')),

    CONSTRAINT CK_REVIEW_VIEW_COUNT
        CHECK (VIEW_COUNT >= 0),

    CONSTRAINT CK_REVIEW_DELETED
        CHECK (IS_DELETED IN ('Y', 'N'))
);

-- REVIEW_IMAGE: 후기 사진 스토리보드(최대 개수는 API에서 8장으로 제한)
CREATE TABLE REVIEW_IMAGE (
    /* 후기 한 건에 연결된 여러 장의 사진을 URL과 표시 순서별로 저장하는 사진 스토리보드 테이블이다. */
    /* 후기 사진 행을 구분하는 자동 증가 기본키 */
    REVIEW_IMAGE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REVIEW_IMAGE PRIMARY KEY,

    /* 사진이 속한 후기 번호(REVIEW 참조) */
    REVIEW_ID NUMBER NOT NULL,
    /* 서버 uploads 또는 외부 저장소에 저장된 실제 사진 주소 */
    IMAGE_URL VARCHAR2(1000) NOT NULL,
    /* 후기 상세 화면에서 사진을 보여 줄 순서(1부터 시작) */
    DISPLAY_ORDER NUMBER NOT NULL,
    /* 사진 정보가 등록된 일시 */
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_REVIEW_IMAGE_REVIEW
        FOREIGN KEY (REVIEW_ID)
        REFERENCES REVIEW(REVIEW_ID)
        ON DELETE CASCADE,

    CONSTRAINT UK_REVIEW_IMAGE_ORDER
        UNIQUE (REVIEW_ID, DISPLAY_ORDER),

    CONSTRAINT CK_REVIEW_IMAGE_ORDER
        CHECK (DISPLAY_ORDER >= 1)
);

-- REVIEW_TAG: 후기 검색·필터에 사용하는 태그
CREATE TABLE REVIEW_TAG (
    /* 후기 검색과 필터에 활용하는 해시태그 성격의 단어를 후기별로 저장한다. */
    /* 후기 태그 행을 구분하는 자동 증가 기본키 */
    REVIEW_TAG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REVIEW_TAG PRIMARY KEY,

    /* 태그가 연결된 후기 번호(REVIEW 참조) */
    REVIEW_ID NUMBER NOT NULL,
    /* 예: 카페, 데이트, 야경처럼 검색에 사용할 태그 이름 */
    TAG_NAME VARCHAR2(30) NOT NULL,

    CONSTRAINT FK_REVIEW_TAG_REVIEW
        FOREIGN KEY (REVIEW_ID)
        REFERENCES REVIEW(REVIEW_ID)
        ON DELETE CASCADE,

    CONSTRAINT UK_REVIEW_TAG
        UNIQUE (REVIEW_ID, TAG_NAME)
);

-- REVIEW_LIKE
-- 좋아요 수만 저장하면 누가 눌렀는지 확인할 수 없으므로 회원별 좋아요를 별도 저장
CREATE TABLE REVIEW_LIKE (
    /* 회원이 특정 후기에 좋아요를 누른 사실을 한 행으로 저장해 중복 좋아요를 막는다. */
    /* 좋아요 기록을 구분하는 자동 증가 기본키 */
    LIKE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REVIEW_LIKE PRIMARY KEY,

    /* 좋아요를 받은 후기 번호(REVIEW 참조) */
    REVIEW_ID NUMBER NOT NULL,
    /* 좋아요를 누른 회원 번호(MEMBER 참조) */
    MEMBER_ID NUMBER NOT NULL,

    /* 좋아요를 누른 일시 */
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_REVIEW_LIKE_REVIEW
        FOREIGN KEY (REVIEW_ID)
        REFERENCES REVIEW(REVIEW_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_REVIEW_LIKE_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID)
        ON DELETE CASCADE,

    CONSTRAINT UK_REVIEW_LIKE
        UNIQUE (REVIEW_ID, MEMBER_ID)
);

/* TRUNCATE TABLE review;*/

-- REVIEW_COMMENT
CREATE TABLE REVIEW_COMMENT (
    /* 후기 게시글 아래에 회원이 남기는 댓글과 논리 삭제 상태를 저장한다. */
    /* 댓글을 구분하는 자동 증가 기본키 */
    COMMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REVIEW_COMMENT PRIMARY KEY,

    /* 댓글이 작성된 후기 번호(REVIEW 참조) */
    REVIEW_ID NUMBER NOT NULL,
    /* 댓글을 작성한 회원 번호(MEMBER 참조) */
    MEMBER_ID NUMBER NOT NULL,

    /* 사용자가 입력한 댓글 본문 */
    CONTENT VARCHAR2(500) NOT NULL,

    /* 댓글을 처음 작성한 일시 */
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    /* 댓글을 마지막으로 수정한 일시 */
    UPDATED_AT DATE,

    /* 실제 삭제 대신 숨김 처리 여부(Y/N) */
    IS_DELETED CHAR(1) DEFAULT 'N' NOT NULL,

    CONSTRAINT FK_COMMENT_REVIEW
        FOREIGN KEY (REVIEW_ID)
        REFERENCES REVIEW(REVIEW_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_COMMENT_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),

    CONSTRAINT CK_COMMENT_DELETED
        CHECK (IS_DELETED IN ('Y', 'N'))
);
