CREATE INDEX IDX_PAYMENT_MEMBER
ON PAYMENT(MEMBER_ID);

CREATE INDEX IDX_SURVEY_MEMBER
ON TRAVEL_SURVEY(MEMBER_ID);

CREATE INDEX IDX_ANSWER_SURVEY
ON SURVEY_ANSWER(SURVEY_ID);

CREATE INDEX IDX_PLACES_REGION_CATEGORY
ON PLACES(REGION, CATEGORY);

CREATE INDEX IDX_TYPE_PLACE_CODE
ON TRAVEL_TYPE_PLACE(TRAVEL_CODE);

CREATE INDEX IDX_TYPE_PLACE_PLACE
ON TRAVEL_TYPE_PLACE(PLACE_ID);

CREATE INDEX IDX_COURSE_MEMBER
ON TRAVEL_COURSES(MEMBER_ID);

-- 테마 코스 중복 저장은 백엔드 서비스에서 검사한다.
-- Oracle 환경별 함수 기반 인덱스 호환 문제를 피하기 위해 DB UNIQUE 인덱스는 만들지 않는다.

CREATE INDEX IDX_DETAILS_COURSE
ON COURSE_DETAILS(COURSE_ID);

CREATE INDEX IDX_DETAILS_PLACE
ON COURSE_DETAILS(PLACE_ID);

CREATE INDEX IDX_REVIEW_COURSE
ON REVIEW(COURSE_ID);

CREATE INDEX IDX_REVIEW_IMAGE_REVIEW
ON REVIEW_IMAGE(REVIEW_ID);

CREATE INDEX IDX_REVIEW_TAG_REVIEW
ON REVIEW_TAG(REVIEW_ID);

CREATE INDEX IDX_CHATBOT_MEMBER
ON CHATBOT_HISTORY(MEMBER_ID);

CREATE INDEX IDX_CHATBOT_PAYMENT
ON CHATBOT_HISTORY(PAYMENT_ID);

CREATE INDEX IDX_REVIEW_MEMBER
ON REVIEW(MEMBER_ID);

CREATE INDEX IDX_REVIEW_PLACE
ON REVIEW(PLACE_ID);

CREATE INDEX IDX_REVIEW_LIKE_MEMBER
ON REVIEW_LIKE(MEMBER_ID);

CREATE INDEX IDX_COMMENT_REVIEW
ON REVIEW_COMMENT(REVIEW_ID);

CREATE INDEX IDX_COMMENT_MEMBER
ON REVIEW_COMMENT(MEMBER_ID);

-- 로컬 연동 확인용 테스트 회원: 같은 이메일이 이미 있으면 추가하지 않음

