-- Apply once to an existing database only.
ALTER TABLE COURSE_DETAILS ADD TRANSIT_PATH_TYPE VARCHAR2(20);
ALTER TABLE COURSE_DETAILS ADD ROUTE_ESTIMATED NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE COURSE_DETAILS ADD CONSTRAINT CK_COURSE_DETAILS_ROUTE_ESTIMATED CHECK (ROUTE_ESTIMATED IN (0, 1));
ALTER TABLE COURSE_DETAILS ADD CONSTRAINT CK_COURSE_DETAILS_TRANSIT_PATH CHECK (TRANSIT_PATH_TYPE IS NULL OR TRANSIT_PATH_TYPE IN ('WALKING', 'SUBWAY', 'BUS', 'BUS_SUBWAY'));

