-- Apply once when REVIEW rating is constrained to 1.0~5.0.
ALTER TABLE REVIEW DROP CONSTRAINT CK_REVIEW_RATING;
ALTER TABLE REVIEW ADD CONSTRAINT CK_REVIEW_RATING CHECK (RATING BETWEEN 0.0 AND 5.0);

