-- Apply once to an existing database.
-- Removes unused survey/course links and removes previously auto-created chatbot courses.

ALTER TABLE CHATBOT_HISTORY DROP CONSTRAINT FK_CHATBOT_COURSE;
ALTER TABLE CHATBOT_HISTORY DROP CONSTRAINT FK_CHATBOT_RESULT;

ALTER TABLE CHATBOT_HISTORY DROP COLUMN COURSE_ID;
ALTER TABLE CHATBOT_HISTORY DROP COLUMN RESULT_ID;

DELETE FROM TRAVEL_COURSES WHERE COURSE_TYPE = 'CHATBOT';
COMMIT;
