-- Existing Oracle DB migration for the survey backend.
-- Safe to rerun: adds missing travel fields, backfills defaults, and enforces NOT NULL.
DECLARE
    v_count NUMBER;
    v_nullable VARCHAR2(1);
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TRAVEL_SURVEY'
      AND COLUMN_NAME = 'COMPANION_TYPE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_SURVEY ADD (COMPANION_TYPE VARCHAR2(30))';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TRAVEL_SURVEY'
      AND COLUMN_NAME = 'TRANSPORT_TYPE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_SURVEY ADD (TRANSPORT_TYPE VARCHAR2(30))';
    END IF;

    UPDATE TRAVEL_SURVEY
    SET COMPANION_TYPE = 'SOLO'
    WHERE COMPANION_TYPE IS NULL;

    UPDATE TRAVEL_SURVEY
    SET TRANSPORT_TYPE = 'PUBLIC'
    WHERE TRANSPORT_TYPE IS NULL;

    SELECT NULLABLE INTO v_nullable
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TRAVEL_SURVEY'
      AND COLUMN_NAME = 'COMPANION_TYPE';

    IF v_nullable = 'Y' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_SURVEY MODIFY (COMPANION_TYPE NOT NULL)';
    END IF;

    SELECT NULLABLE INTO v_nullable
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TRAVEL_SURVEY'
      AND COLUMN_NAME = 'TRANSPORT_TYPE';

    IF v_nullable = 'Y' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_SURVEY MODIFY (TRANSPORT_TYPE NOT NULL)';
    END IF;
END;

COMMENT ON COLUMN TRAVEL_SURVEY.COMPANION_TYPE IS '여행 동행 유형';
COMMENT ON COLUMN TRAVEL_SURVEY.TRANSPORT_TYPE IS '여행 전체 이동수단';

COMMIT;
