-- Existing Oracle DB migration: PEOPLE_COUNT is no longer used.
-- Run once in DBeaver or SQL Developer against the existing SEOULINK schema.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TRAVEL_SURVEY'
      AND CONSTRAINT_NAME = 'CK_SURVEY_PEOPLE';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_SURVEY DROP CONSTRAINT CK_SURVEY_PEOPLE';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TRAVEL_SURVEY'
      AND COLUMN_NAME = 'PEOPLE_COUNT';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_SURVEY DROP COLUMN PEOPLE_COUNT';
    END IF;
END;
