-- Safe to rerun: add support for built-in THEME courses.
-- 기존 잘못된 UNIQUE 제약/함수 기반 인덱스는 제거하고,
-- 테마 중복 저장은 백엔드 서비스에서 검사한다.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'TRAVEL_COURSES'
      AND COLUMN_NAME = 'SOURCE_COURSE_KEY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE TRAVEL_COURSES ADD (SOURCE_COURSE_KEY VARCHAR2(50))';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TRAVEL_COURSES'
      AND CONSTRAINT_NAME = 'CK_COURSE_TYPE';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE TRAVEL_COURSES DROP CONSTRAINT CK_COURSE_TYPE';
    END IF;

    EXECUTE IMMEDIATE
        'ALTER TABLE TRAVEL_COURSES ADD CONSTRAINT CK_COURSE_TYPE '
        || 'CHECK (COURSE_TYPE IN (''CUSTOM'', ''SURVEY'', ''CHATBOT'', ''THEME''))';

    SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TRAVEL_COURSES'
      AND CONSTRAINT_NAME = 'UK_MEMBER_SOURCE_COURSE';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE TRAVEL_COURSES DROP CONSTRAINT UK_MEMBER_SOURCE_COURSE';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'UX_MEMBER_THEME_SOURCE_COURSE';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX UX_MEMBER_THEME_SOURCE_COURSE';
    END IF;
END;

COMMENT ON COLUMN TRAVEL_COURSES.COURSE_TYPE IS
    '코스 생성 방식, CUSTOM/SURVEY/CHATBOT/THEME 중 하나';
COMMENT ON COLUMN TRAVEL_COURSES.SOURCE_COURSE_KEY IS
    '회원이 저장한 기본 테마 코스를 식별하는 원본 코스 키, 일반 코스는 NULL';

COMMIT;
