SELECT table_name FROM user_tables WHERE table_name IN ('MEMBER','PLACES','PAYMENT','TRAVEL_SURVEY','SURVEY_QUESTION','SURVEY_OPTION','SURVEY_ANSWER','TRAVEL_TYPE_MASTER','TRAVEL_TYPE_PLACE','SURVEY_RESULT','TRAVEL_COURSES','COURSE_DETAILS','CHATBOT_HISTORY','REVIEW','REVIEW_IMAGE','REVIEW_TAG','REVIEW_LIKE','REVIEW_COMMENT') ORDER BY table_name;

