SELECT 'MEMBER' AS target, COUNT(*) AS total FROM MEMBER UNION ALL SELECT 'PLACES', COUNT(*) FROM PLACES UNION ALL SELECT 'TRAVEL_TYPE_MASTER', COUNT(*) FROM TRAVEL_TYPE_MASTER UNION ALL SELECT 'SURVEY_QUESTION', COUNT(*) FROM SURVEY_QUESTION UNION ALL SELECT 'SURVEY_OPTION', COUNT(*) FROM SURVEY_OPTION;

