-- seoul-link-back(52) 필수 컬럼 검증
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE (TABLE_NAME = 'TRAVEL_SURVEY'
       AND COLUMN_NAME IN ('COMPANION_TYPE', 'TRANSPORT_TYPE'))
   OR (TABLE_NAME = 'TRAVEL_COURSES'
       AND COLUMN_NAME = 'IS_SAVED')
   OR (TABLE_NAME = 'COURSE_DETAILS'
       AND COLUMN_NAME IN ('TRANSIT_PATH_TYPE', 'ROUTE_ESTIMATED'))
ORDER BY TABLE_NAME, COLUMN_NAME;

-- 제거되어야 하는 과거 컬럼 검증: 결과가 0행이면 정상
SELECT TABLE_NAME, COLUMN_NAME
FROM USER_TAB_COLUMNS
WHERE (TABLE_NAME = 'TRAVEL_SURVEY' AND COLUMN_NAME = 'PEOPLE_COUNT')
   OR (TABLE_NAME = 'TRAVEL_COURSES' AND COLUMN_NAME IN ('TRANSPORT_MODE', 'OPTIMIZATION_TYPE'))
   OR (TABLE_NAME = 'COURSE_DETAILS' AND COLUMN_NAME IN ('MOVE_DISTANCE_M', 'MOVE_DURATION_MIN'));
