SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'MEMBER'
  AND COLUMN_NAME IN ('LOGIN_TYPE', 'SOCIAL_PROVIDER', 'SOCIAL_ID')
ORDER BY COLUMN_NAME;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'MEMBER'
  AND CONSTRAINT_NAME IN (
      'UK_MEMBER_SOCIAL',
      'CK_MEMBER_LOGIN_TYPE',
      'CK_MEMBER_SOCIAL_PROVIDER',
      'CK_MEMBER_LOGIN_RULE'
  )
ORDER BY CONSTRAINT_NAME;
