-- 결과가 0행이면 PEOPLE_COUNT와 과거 제약조건이 제거된 상태입니다.
SELECT COLUMN_NAME
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'TRAVEL_SURVEY'
  AND COLUMN_NAME = 'PEOPLE_COUNT';

SELECT CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TRAVEL_SURVEY'
  AND CONSTRAINT_NAME = 'CK_SURVEY_PEOPLE';
