-- 챗봇 대화방 컬럼과 인덱스
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'CHATBOT_HISTORY'
  AND COLUMN_NAME = 'CONVERSATION_ID';

SELECT INDEX_NAME, TABLE_NAME
FROM USER_INDEXES
WHERE INDEX_NAME = 'IDX_CHATBOT_HISTORY_MEMBER_CONVERSATION';

-- 후기 동행 유형 제약조건
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'REVIEW'
  AND CONSTRAINT_NAME = 'CK_REVIEW_COMPANION';

SELECT COMPANION, COUNT(*) AS CNT
FROM REVIEW
GROUP BY COMPANION
ORDER BY COMPANION;

-- 결제 금액 정수 타입과 결제키 유일 제약조건
SELECT COLUMN_NAME, DATA_TYPE, DATA_PRECISION, DATA_SCALE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'PAYMENT'
  AND COLUMN_NAME = 'AMOUNT';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PAYMENT'
  AND CONSTRAINT_NAME = 'UK_PAYMENT_KEY';
