-- 테마 코스 저장용 컬럼
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'TRAVEL_COURSES'
  AND COLUMN_NAME = 'SOURCE_COURSE_KEY';

-- COURSE_TYPE이 THEME을 허용하는지 확인
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TRAVEL_COURSES'
  AND CONSTRAINT_NAME = 'CK_COURSE_TYPE';

-- 아래 두 조회는 모두 0행이어야 정상
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TRAVEL_COURSES'
  AND CONSTRAINT_NAME = 'UK_MEMBER_SOURCE_COURSE';

SELECT INDEX_NAME, UNIQUENESS, STATUS
FROM USER_INDEXES
WHERE INDEX_NAME = 'UX_MEMBER_THEME_SOURCE_COURSE';

-- 혹시 기존 테마 중복 데이터가 있는지 확인
SELECT MEMBER_ID, SOURCE_COURSE_KEY, COUNT(*) AS CNT
FROM TRAVEL_COURSES
WHERE COURSE_TYPE = 'THEME'
  AND SOURCE_COURSE_KEY IS NOT NULL
GROUP BY MEMBER_ID, SOURCE_COURSE_KEY
HAVING COUNT(*) > 1;
